CREATE ACCOUNT HM_DEV
    ADMIN_NAME = <EXISTING_USER_HERE>
    ADMIN_PASSWORD = '<PASSWORD_HERE>'
    EMAIL = '<EMAIL_HERE>'
    MUST_CHANGE_PASSWORD = FALSE
    EDITION = ENTERPRISE
    ;

USE ROLE ACCOUNTADMIN;

CREATE USER HM_ADMIN
    PASSWORD='<PASSWORD_HERE>'
    DEFAULT_ROLE = SYSADMIN
    DEFAULT_SECONDARY_ROLES = ('ALL')
    MUST_CHANGE_PASSWORD = FALSE
    LOGIN_NAME = HM_ADMIN
    DISPLAY_NAME = HM_ADMIN
    FIRST_NAME = HM_ADMIN
    LAST_NAME = HM_ADMIN
    ;

-- grant roles
GRANT ROLE ACCOUNTADMIN, SYSADMIN TO USER HM_ADMIN;

-- set default role to sysadmin
ALTER USER HM_ADMIN SET DEFAULT_ROLE=SYSADMIN;