name: app_environment
channels:
  - snowflake
dependencies:
  - numpy=*
  - tabulate=*
  - pydantic=*
  - pydantic-core
  - sqlalchemy=*
  - python-graphviz=*
  - cryptography=*
  - pydot=*
  - certifi=*
